package com.shu.mapper;

import com.shu.pojo.ChatMsg;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ChatMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_msg
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_msg
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    int insert(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_msg
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    ChatMsg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_msg
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    List<ChatMsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chat_msg
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    int updateByPrimaryKey(ChatMsg record);
}