package com.shu.mapper;

import com.shu.pojo.FrientRequest;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface FrientRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_frient_request
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_frient_request
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    int insert(FrientRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_frient_request
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    FrientRequest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_frient_request
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    List<FrientRequest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_frient_request
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    int updateByPrimaryKey(FrientRequest record);
}