package com.shu.mapper;

import com.shu.pojo.User;
import com.shu.pojo.vo.FriendRequestVO;
import com.shu.pojo.vo.MyFriendVO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface UserMapper {

    int deleteByPrimaryKey(String id);


    int insert(User record);


    User selectByPrimaryKey(String id);


    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    int updateByPrimaryKey(User record);

    User selectOne(User user);

    // 验证用户名和密码是否匹配
    User varifyUser(User user);

    // 查询好友请求列表
    List<FriendRequestVO> queryFriendRequest(String acceptUserId );

    // 查询好友列表
    List<MyFriendVO> queryMyFriends(String userId);

    // 批量签收消息
    void batchUpdateMsgSigned(List<String> msgIdList);
}