package com.shu.pojo;

public class Garbage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_garbage.garbage_name
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    private String garbageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_garbage.id
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_garbage.garbage_id
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    private String garbageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_garbage.garbage_category
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    private Integer garbageCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_garbage.garbage_description
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    private String garbageDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_garbage.garbage_name
     *
     * @return the value of t_garbage.garbage_name
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    public String getGarbageName() {
        return garbageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_garbage.garbage_name
     *
     * @param garbageName the value for t_garbage.garbage_name
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    public void setGarbageName(String garbageName) {
        this.garbageName = garbageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_garbage.id
     *
     * @return the value of t_garbage.id
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_garbage.id
     *
     * @param id the value for t_garbage.id
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_garbage.garbage_id
     *
     * @return the value of t_garbage.garbage_id
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    public String getGarbageId() {
        return garbageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_garbage.garbage_id
     *
     * @param garbageId the value for t_garbage.garbage_id
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    public void setGarbageId(String garbageId) {
        this.garbageId = garbageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_garbage.garbage_category
     *
     * @return the value of t_garbage.garbage_category
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    public Integer getGarbageCategory() {
        return garbageCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_garbage.garbage_category
     *
     * @param garbageCategory the value for t_garbage.garbage_category
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    public void setGarbageCategory(Integer garbageCategory) {
        this.garbageCategory = garbageCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_garbage.garbage_description
     *
     * @return the value of t_garbage.garbage_description
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    public String getGarbageDescription() {
        return garbageDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_garbage.garbage_description
     *
     * @param garbageDescription the value for t_garbage.garbage_description
     *
     * @mbggenerated Tue Aug 25 12:48:59 CST 2020
     */
    public void setGarbageDescription(String garbageDescription) {
        this.garbageDescription = garbageDescription;
    }
}